apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apply-pods
  namespace: nalms-test
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: pod-updater
  apiGroup: rbac.authorization.k8s.io
