apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nalms-test
  name: pod-updater
rules:
- apiGroups: ["", "apps"] # "" indicates the core API group
  resources: ["pods", "configmaps", "statefulsets"]
  verbs: ["get", "watch", "list", "apply", "create", "delete", "patch"]
