apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-server-watcher
  labels:
    app: alarm-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarm-watcher
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alarm-watcher
    spec:
      serviceAccountName: internal-kubectl
      containers:
        - image: tidacs/alarm-server-updater:v1.3
          name: alarm-server-watcher
          env:
            - name: GIT_REPO
              value: https://github.com/slaclab/nalms-deployment
            - name: GIT_REPO_NAME
              value: nalms-deployment
          resources: {}
      restartPolicy: Always
status: {}
