# This workflow will validate all xml files on any PR or push to main. Errors will be logged, and a
# non-zero exit code will be displayed as a failure that needs to be fixed.

name: Validate XML

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install package needed for linting an xml file
      run: sudo apt-get install libxml2-utils
    - name: Install python requirements
      run: |
        pip install --upgrade pip
        pip install --requirement dev-requirements.txt
    - name: Validate Phoebus will parse xml correctly
      run: python xml/validate_xml_for_phoebus.py
    - name: Lint with xmllint
      run: ./xml/lint_xml.sh
      shell: bash
